// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_CxMv35HNfxlZYl2DZGXdm2ZeAQsVL8I',
    appId: '1:3449345393:web:c5f49ccb339ee3b01a92d0',
    messagingSenderId: '3449345393',
    projectId: 'foods-24',
    authDomain: 'foods-24.firebaseapp.com',
    storageBucket: 'foods-24.firebasestorage.app',
    measurementId: 'G-028R9TLWZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhXZ91fx7QES7otgFG0AXmGGezHLmjVFU',
    appId: '1:3449345393:android:088971265be5ba5f1a92d0',
    messagingSenderId: '3449345393',
    projectId: 'foods-24',
    storageBucket: 'foods-24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEPhD1cTgJnYRYSTvGONBEmX0zVq7Yl24',
    appId: '1:3449345393:ios:f2a2f41aab806bc71a92d0',
    messagingSenderId: '3449345393',
    projectId: 'foods-24',
    storageBucket: 'foods-24.firebasestorage.app',
    iosClientId: '3449345393-j3revqvvn90hev58itahk3q24d4m0hma.apps.googleusercontent.com',
    iosBundleId: 'com.example.foods24Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEPhD1cTgJnYRYSTvGONBEmX0zVq7Yl24',
    appId: '1:3449345393:ios:f2a2f41aab806bc71a92d0',
    messagingSenderId: '3449345393',
    projectId: 'foods-24',
    storageBucket: 'foods-24.firebasestorage.app',
    iosClientId: '3449345393-j3revqvvn90hev58itahk3q24d4m0hma.apps.googleusercontent.com',
    iosBundleId: 'com.example.foods24Firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_CxMv35HNfxlZYl2DZGXdm2ZeAQsVL8I',
    appId: '1:3449345393:web:f0d08bc20094087d1a92d0',
    messagingSenderId: '3449345393',
    projectId: 'foods-24',
    authDomain: 'foods-24.firebaseapp.com',
    storageBucket: 'foods-24.firebasestorage.app',
    measurementId: 'G-NRB0JTKV1V',
  );
}
